application: not-a-treadstone-drill
version: 1
runtime: python27
api_version: 1
threadsafe: true
libraries:
- name: jinja2
  version: latest


handlers:

- url: /stylesheets
  static_dir: stylesheets
  
- url: /.*
  script: routes.app